In [1]:
# (4)2b-4S/C(4)
import tensorflow as tf

x_data = [[0., 0], [0, 1], [1, 0], [1, 1]]
y_data = [[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]]

#------- 2 inputs 4 neurons
W = tf.Variable(tf.random_normal([2, 4]))
b = tf.Variable(tf.random_normal([4]))
output = tf.matmul(x_data, W) + b  # logit (?, 4)

#----- learning
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=output,
                                                              labels=y_data))

train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train)

    if step % 500 == 0:
        print(step, sess.run(cost))

#----- testing(classification)
logit = sess.run(output) #(?, 4)
print("\nLogits: ", logit)

hit = tf.equal(tf.argmax(output, 1), tf.argmax(y_data, 1))
accuracy = tf.reduce_mean(tf.cast(hit, tf.float32))

p = sess.run(hit)
print("\nhit: ", p)

a = sess.run(accuracy)
print("Accuracy(%): ", a * 100)


Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

0 1.7620447
500 0.149854
1000 0.05051747
1500 0.025284262
2000 0.014963509
2500 0.00968879
3000 0.006626352
3500 0.004697625
4000 0.0034136104
4500 0.002524635
5000 0.0018911306
5500 0.0014300821
6000 0.0010891868
6500 0.0008339674
7000 0.0006411399
7500 0.00049447676
8000 0.00038229054
8500 0.00029604216
9000 0.00022954088
9500 0.00017823177
10000 0.00013851159

Logits:  [[  5.8745375  -4.8385997  -3.1161642  -9.339852 ]
 [ -3.032236    7.4541183 -15.819788   -1.7428088]
 [ -1.8931952 -16.15471     7.4729204  -2.3388023]
 [-10.79997    -3.8619924  -5.2307034   5.2582407]]

hit:  [ True  True  True  True]
Accuracy(%):  100.0
