In [1]:
# (4)2b-4S/C(4)
import tensorflow as tf

x_data = [[0., 0], [0, 1], [1, 0], [1, 1]]
y_data = [[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]]

X = tf.placeholder(tf.float32, [4, 2])
Y = tf.placeholder(tf.float32, [4, 4])

#------- 2 inputs 4 neurons
W = tf.Variable(tf.random_normal([2, 4]))
b = tf.Variable(tf.random_normal([4]))
output = tf.matmul(X, W) + b

#----- learning
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=output,
                                                              labels=Y))

train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(10001):
    sess.run(train, feed_dict={X:x_data, Y:y_data})

    if step % 500 == 0:
        print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))

#----- testing(classification)
predicted = tf.equal(tf.argmax(output, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(predicted, tf.float32))

h = sess.run(output, feed_dict={X:x_data})
print("\nLogits: ", h)

p = sess.run(predicted, feed_dict={X:x_data, Y:y_data})
print("Predicted: ", p)

a = sess.run(accuracy, feed_dict={X:x_data, Y:y_data})
print("Accuracy(%): ", a * 100)


Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

0 1.5163966
500 0.108895935
1000 0.03751074
1500 0.018937275
2000 0.011249129
2500 0.0072967196
3000 0.004994683
3500 0.003542238
4000 0.0025743772
4500 0.0019038753
5000 0.0014260816
5500 0.001078237
6000 0.0008210895
6500 0.0006285334
7000 0.00048318243
7500 0.000372546
8000 0.00028793656
8500 0.00022295503
9000 0.00017286767
9500 0.00013419046
10000 0.00010427265

Logits:  [[ 1.0934862e+01 -8.4874302e-01  1.7581849e+00 -9.9991064e+00]
 [-3.6249876e+00  7.5096231e+00 -1.1116148e+01 -2.0887661e+00]
 [ 5.3834629e-01 -1.0057068e+01  9.8899498e+00 -1.2503624e-02]
 [-1.4021503e+01 -1.6987014e+00 -2.9843841e+00  7.8978357e+00]]
Predicted:  [ True  True  True  True]
Accuracy(%):  100.0
